# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_get_patent_status_codes

Search USPTO patent application status codes and their descriptions. Returns the code-to-description mapping used in application status fields. Optionally filter with a query string.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_get_patent_status_codes(
    q: Optional[str] = None,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Search USPTO patent application status codes and their descriptions. Returns the code-to-description mapping used in application status fields. Optionally filter with a query string.

    Parameters
    ----------
    q : str
        Search query string (e.g., 'Abandoned' or a status code).

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_get_patent_status_codes",
            "arguments": {"q": q},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_get_patent_status_codes"]
