# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_get_ptab_proceeding

Get a PTAB trial proceeding by trial number (e.g. 'IPR2015-00001').
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_get_ptab_proceeding(
    trialNumber: str,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Get a PTAB trial proceeding by trial number (e.g. 'IPR2015-00001').

    Parameters
    ----------
    trialNumber : str
        Trial number, e.g. 'IPR2015-00001'.

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_get_ptab_proceeding",
            "arguments": {"trialNumber": trialNumber},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_get_ptab_proceeding"]
