# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_get_patent_attorney

Get the attorney/agent of record for a US patent application. Returns the registered attorney or agent associated with the application. Requires an application number (e.g., '14966067') -- use USPTO_patent_number_to_application to convert patent numbers first.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_get_patent_attorney(
    applicationNumberText: str,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Get the attorney/agent of record for a US patent application. Returns the registered attorney or agent associated with the application. Requires an application number (e.g., '14966067') -- use USPTO_patent_number_to_application to convert patent numbers first.

    Parameters
    ----------
    applicationNumberText : str
        The application number of the patent (e.g., '14966067'). This is NOT the patent number -- use USPTO_patent_number_to_application to convert.

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_get_patent_attorney",
            "arguments": {"applicationNumberText": applicationNumberText},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_get_patent_attorney"]
