# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_search_appeal_decisions

Search PTAB appeal decisions with a JSON-body POST (Lucene query). Returns decision records for ex parte appeals.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_search_appeal_decisions(
    query: str,
    offset: Optional[int] = None,
    limit: Optional[int] = None,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Search PTAB appeal decisions with a JSON-body POST (Lucene query). Returns decision records for ex parte appeals.

    Parameters
    ----------
    query : str
    offset : int
    limit : int

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_search_appeal_decisions",
            "arguments": {"query": query, "offset": offset, "limit": limit},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_search_appeal_decisions"]
