# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_search_patent_status_codes

Search USPTO patent application status codes and descriptions with a JSON-body POST. Returns the code-to-description mapping (e.g. 165 = ABANDONED - RESTORED). Query with Lucene syntax, e.g. 'applicationStatusDescriptionText:Abandoned'.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_search_patent_status_codes(
    query: str,
    offset: Optional[int] = None,
    limit: Optional[int] = None,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Search USPTO patent application status codes and descriptions with a JSON-body POST. Returns the code-to-description mapping (e.g. 165 = ABANDONED - RESTORED). Query with Lucene syntax, e.g. 'applicationStatusDescriptionText:Abandoned'.

    Parameters
    ----------
    query : str
        Lucene query string, e.g. 'applicationStatusDescriptionText:Abandoned'.
    offset : int
        Position in the dataset to start from (default 0).
    limit : int
        Maximum number of results to return (default 25).

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_search_patent_status_codes",
            "arguments": {"query": query, "offset": offset, "limit": limit},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_search_patent_status_codes"]
