# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_get_enriched_citation_fields

List the searchable fields of the USPTO Enriched Citation dataset (enriched_cited_reference_metadata v3). Returns the field list, dataset status, and last data update date. Use this first to learn which fields are queryable before searching citations with USPTO_search_enriched_citations. The API is the USPTO Open Data Portal DSAPI; data covers office actions mailed from 2017-10-01 to 30 days before the current date.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_get_enriched_citation_fields(
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    List the searchable fields of the USPTO Enriched Citation dataset (enriched_cited_reference_metadata v3). Returns the field list, dataset status, and last data update date. Use this first to learn which fields are queryable before searching citations with USPTO_search_enriched_citations. The API is the USPTO Open Data Portal DSAPI; data covers office actions mailed from 2017-10-01 to 30 days before the current date.

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_get_enriched_citation_fields",
            "arguments": {},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_get_enriched_citation_fields"]
