# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_get_patent_documents

Get document details for a US patent application. Returns metadata for documents in the application file wrapper (e.g., office actions, responses, fee worksheets). Optionally filter by document codes and official date range. Requires an application number (e.g., '14966067') -- use USPTO_patent_number_to_application to convert patent numbers first.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_get_patent_documents(
    applicationNumberText: str,
    documentCodes: Optional[str] = None,
    officialDateFrom: Optional[str] = None,
    officialDateTo: Optional[str] = None,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Get document details for a US patent application. Returns metadata for documents in the application file wrapper (e.g., office actions, responses, fee worksheets). Optionally filter by document codes and official date range. Requires an application number (e.g., '14966067') -- use USPTO_patent_number_to_application to convert patent numbers first.

    Parameters
    ----------
    applicationNumberText : str
        The application number of the patent (e.g., '14966067'). This is NOT the patent number -- use USPTO_patent_number_to_application to convert.
    documentCodes : str
        Single or multiple comma-separated document codes (e.g., 'SRFW,SRNT' for search reports, 'WFEE' for fee worksheet).
    officialDateFrom : str
        Filter by document official date from, format yyyy-MM-dd.
    officialDateTo : str
        Filter by document official date to, format yyyy-MM-dd.

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_get_patent_documents",
            "arguments": {"applicationNumberText": applicationNumberText, "documentCodes": documentCodes, "officialDateFrom": officialDateFrom, "officialDateTo": officialDateTo},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_get_patent_documents"]
