# AUTO-GENERATED by `tu build` — do not edit manually
"""USPTO_get_ptab_decision

Get a PTAB trial decision by document identifier.
"""

from typing import Any, Callable, Optional

from ._shared_client import get_shared_client


def USPTO_get_ptab_decision(
    documentIdentifier: str,
    *,
    stream_callback: Optional[Callable[[str], None]] = None,
    use_cache: bool = False,
    validate: bool = True,
) -> dict[str, Any]:
    """
    Get a PTAB trial decision by document identifier.

    Parameters
    ----------
    documentIdentifier : str

    stream_callback : Callable, optional
        Callback for streaming output
    use_cache : bool, default False
        Enable caching
    validate : bool, default True
        Validate parameters

    Returns
    -------
    dict[str, Any]
    """
    return get_shared_client().run_one_function(
        {
            "name": "USPTO_get_ptab_decision",
            "arguments": {"documentIdentifier": documentIdentifier},
        },
        stream_callback=stream_callback,
        use_cache=use_cache,
        validate=validate,
    )


__all__ = ["USPTO_get_ptab_decision"]
